const $ = (selector) => document.querySelector(selector);
const screens = { portal: $('#portal-screen'), success: $('#success-screen'), limited: $('#limited-screen'), verify: $('#verify-screen'), userLogin: $('#user-login-screen'), login: $('#login-screen'), dashboard: $('#dashboard-screen') };
const captiveContext = Object.fromEntries(['client_mac','client_ip','ssid','login_url','logout_url','orig_url'].map(key => [key, new URLSearchParams(location.search).get(key) || '']));
let verificationToken = new URLSearchParams(location.search).get('verify');
async function api(path, payload) { const response = await fetch(path, { method: payload ? 'POST' : 'GET', headers: payload ? { 'content-type': 'application/json' } : undefined, body: payload ? JSON.stringify(payload) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Permintaan gagal.'); return result; }
function handleAuthorization(result, fallback) { if (result?.authorization?.mode === 'redirect') { location.assign(result.authorization.url); return; } fallback(); }
const leads = [
  { name:'Kadek Ayu Lestari', email:'kadek.ayu@email.com', phone:'0812 3456 7890', address:'Karangasem, Bali', time:'Hari ini, 10:42', initials:'KA', type:'high' },
  { name:'I Made Aditya', email:'made.aditya@email.com', phone:'0852 7901 2841', address:'Amlapura, Bali', time:'Hari ini, 10:18', initials:'MA', type:'high' },
  { name:'Guest One-Click', email:'Data tidak diisi', phone:'—', address:'—', time:'Hari ini, 09:56', initials:'OC', type:'limited' },
  { name:'Komang Surya', email:'komang.surya@email.com', phone:'0877 4125 6309', address:'Manggis, Bali', time:'Hari ini, 09:31', initials:'KS', type:'high' },
  { name:'Guest One-Click', email:'Data tidak diisi', phone:'—', address:'—', time:'Kemarin, 16:24', initials:'OC', type:'limited' },
  { name:'Wayan Saputra', email:'wayan.saputra@email.com', phone:'0857 6093 1128', address:'Abang, Bali', time:'Kemarin, 15:48', initials:'WS', type:'high' }
];
function show(screen) { Object.values(screens).forEach(el => el.classList.remove('active')); screens[screen].classList.add('active'); window.scrollTo(0,0); }
function showAccessChoice() { $('#portal-screen').classList.remove('show-form'); show('portal'); }
function showLeadForm() { $('#portal-screen').classList.add('show-form'); show('portal'); }
function showUserLogin() { show('userLogin'); }
function connectToWifi(withLead) { const wifi = $('#wifi-name').textContent; $('#success-wifi').textContent = wifi; $('#success-message').textContent = withLead ? 'Data Anda telah tersimpan dan akses internet sudah aktif. Selamat berselancar.' : 'Akses internet Anda sudah aktif. Selamat berselancar dengan WiFi gratis PerumNet.'; show('success'); }
function connectLimited() { $('#limited-wifi').textContent = $('#wifi-name').textContent; show('limited'); }
async function loadAdminLeads() { const rows = await api('/api/admin/leads'); leads.splice(0, leads.length, ...rows.map(row => ({ name:row.full_name || 'Guest One-Click', email:row.email || 'Data tidak diisi', phone:row.phone_number || '—', address:row.address || '—', time:new Date(row.timestamp).toLocaleString('id-ID'), initials:row.full_name ? row.full_name.split(' ').slice(0,2).map(part => part[0]).join('') : 'OC', type:row.access_type === 'high_speed' ? 'high' : 'limited', verified:!!row.is_verified }))); renderLeads(); }
function renderLeads(data=leads) { $('#lead-rows').innerHTML = data.map(l => `<tr><td><div class="user-cell"><span class="avatar">${l.initials}</span><div><b>${l.name}</b><span>${l.email}</span>${l.type === 'high' && l.verified !== false ? '<em class="verified-status">✓ Email terverifikasi</em>' : ''}</div></div></td><td>${l.phone}</td><td><span class="access-badge ${l.type}">${l.type === 'high' ? 'High Speed' : 'Limited'}</span></td><td>${l.address}</td><td>${l.time}</td><td class="more">•••</td></tr>`).join('') || '<tr><td colspan="6" class="empty-state">Belum ada aktivitas akses.</td></tr>'; $('#result-count').textContent = data.length === leads.length ? `Menampilkan ${data.length} data` : `Menampilkan ${data.length} hasil pencarian`; }
renderLeads();
if (verificationToken) { api('/api/auth/verify', { token:verificationToken, context:captiveContext }).then(result => handleAuthorization(result, () => connectToWifi(true))).catch(error => alert(error.message)); }
$('#lead-form').addEventListener('submit', async e => { e.preventDefault(); const data = new FormData(e.currentTarget); if (![...data.values()].every(Boolean)) { $('#form-error').textContent = 'Lengkapi semua data, kata sandi, dan setujui syarat terlebih dahulu.'; return; } try { const result = await api('/api/auth/register', { fullName:data.get('name'), email:data.get('email'), phone:data.get('phone'), address:data.get('address'), password:data.get('password'), consent:data.get('consent'), context:captiveContext }); $('#form-error').textContent=''; $('#verification-email').textContent = result.email; verificationToken = result.verificationUrl ? new URL(result.verificationUrl).searchParams.get('verify') : null; show('verify'); } catch (error) { $('#form-error').textContent = error.message; } });
$('#choose-high-speed').onclick = showLeadForm; $('#back-to-access-choice').onclick = showAccessChoice; $('#choose-limited').onclick = async () => { try { const result = await api('/api/captive/limited', { context:captiveContext }); $('#limited-bandwidth').textContent = `${result.bandwidthKbps} Kbps`; handleAuthorization(result, connectLimited); } catch (error) { alert(error.message); } };
$('#quick-login-form').addEventListener('submit', async e => { e.preventDefault(); const fields = e.currentTarget.querySelectorAll('input'); try { const result = await api('/api/auth/login', { email:fields[0].value, password:fields[1].value, context:captiveContext }); handleAuthorization(result, () => connectToWifi(true)); } catch (error) { alert(error.message); } });
$('#open-user-login').onclick = showUserLogin; $('#back-from-user-login').onclick = showAccessChoice;
$('#user-login-form').addEventListener('submit', async e => { e.preventDefault(); const fields = e.currentTarget.querySelectorAll('input'); try { const result = await api('/api/auth/login', { email:fields[0].value, password:fields[1].value, context:captiveContext }); handleAuthorization(result, () => connectToWifi(true)); } catch (error) { alert(error.message); } });
$('#simulate-verification').onclick = async () => { if (!verificationToken) return alert('Buka tautan verifikasi yang dikirim ke email Anda.'); try { const result = await api('/api/auth/verify', { token:verificationToken, context:captiveContext }); handleAuthorization(result, () => connectToWifi(true)); } catch (error) { alert(error.message); } }; $('#back-from-verify').onclick = showAccessChoice;
$('#return-portal').onclick = showAccessChoice; $('#browse-button').onclick = () => alert('Akses internet kecepatan penuh telah aktif. Selamat browsing!');
$('#upgrade-access').onclick = showLeadForm; $('#continue-limited').onclick = () => alert('Akses terbatas tetap aktif. Selamat browsing!');
$('#admin-trigger').onclick = e => { e.preventDefault(); show('login'); }; $('#access-admin-trigger').onclick = e => { e.preventDefault(); show('login'); }; $('#back-portal').onclick = showAccessChoice;
$('#login-form').addEventListener('submit', async e => { e.preventDefault(); const fields = e.currentTarget.querySelectorAll('input'); try { await api('/api/admin/login', { email:fields[0].value, password:fields[1].value }); await loadAdminLeads(); show('dashboard'); } catch (error) { alert(error.message); } }); $('#logout').onclick = showAccessChoice;
document.querySelectorAll('.nav-item').forEach(item => item.onclick = () => { document.querySelectorAll('.nav-item').forEach(i=>i.classList.remove('active')); item.classList.add('active'); const tab=item.dataset.tab; document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active')); $(`#${tab}-tab`).classList.add('active'); $('#dash-title').textContent=tab==='leads'?'Data Pengunjung':'Pengaturan Portal'; });
$('#search-input').addEventListener('input', e => { const q=e.target.value.toLowerCase(); renderLeads(leads.filter(l => `${l.name} ${l.email}`.toLowerCase().includes(q))); });
$('#export-csv').onclick = () => { const csv=['Nama,Email,Nomor WhatsApp,Tipe Akses,Alamat,Waktu Akses',...leads.map(l=>`"${l.name}",${l.email},"${l.phone}",${l.type === 'high' ? 'High Speed' : 'Limited'},"${l.address}","${l.time}"`)].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='data-pengunjung-kopi-pagi.csv'; a.click(); URL.revokeObjectURL(a.href); };
$('#settings-form').addEventListener('submit', e => { e.preventDefault(); const wifi=$('#setting-wifi').value || 'Kopi Pagi Guest', title=$('#setting-title').value || 'Terhubung dalam hitungan detik.', copy=$('#setting-copy').value; $('#wifi-name').textContent=wifi; $('#success-wifi').textContent=wifi; $('#preview-title').textContent=title; $('#preview-copy').textContent=copy; const b=e.currentTarget.querySelector('button'); const old=b.innerHTML; b.innerHTML='Tersimpan ✓'; setTimeout(()=>b.innerHTML=old,1600); });
