import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const [html, css, app, favicon] = await Promise.all([
  readFile(new URL('../index.html', import.meta.url), 'utf8'),
  readFile(new URL('../styles.css', import.meta.url), 'utf8'),
  readFile(new URL('../app.js', import.meta.url), 'utf8'),
  readFile(new URL('../assets/perumnet-favicon.png', import.meta.url))
]);

assert.match(html, /id="success-screen" class="success-page portal-modal"/, 'Status koneksi harus memakai modal.');
assert.match(html, /id="free-screen" class="free-page"/, 'Portal harus menyediakan halaman khusus one-click di /free.');
assert.match(html, /id="free-connect"[^>]*type="button"/, 'Halaman free harus menyediakan satu tombol koneksi tanpa formulir.');
assert.doesNotMatch(html, /id="choose-limited"/, 'Portal akun utama tidak boleh lagi menampilkan pilihan one-click.');
assert.match(html, /id="setting-account-ssid" value="@PERUMNET_WiFi"/, 'Admin harus menyediakan SSID khusus portal akun.');
assert.match(html, /id="setting-free-ssid" value="@PERUMNET_FreeWiFi"/, 'Admin harus menyediakan SSID khusus portal gratis.');
assert.match(html, /class="portal-profile-card account"/, 'Admin harus menjelaskan profil portal akun.');
assert.match(html, /class="portal-profile-card free"/, 'Admin harus menjelaskan profil portal free.');
assert.match(html, /id="user-login-screen" class="login-page portal-modal"/, 'Login pelanggan harus memakai modal.');
assert.match(html, /id="sidebar-toggle"/, 'Dashboard harus menyediakan tombol navigasi mobile.');
assert.match(html, /id="workspace-toggle"[^>]*aria-haspopup="menu"[^>]*aria-expanded="false"/, 'Kartu workspace harus menjadi tombol pemilih project dan gateway yang accessible.');
assert.match(html, /id="workspace-menu"[^>]*aria-label="Pilih project atau gateway"/, 'Sidebar harus menyediakan menu pemilih jaringan yang nyata.');
assert.match(html, /id="workspace-options"[^>]*role="menu"/, 'Pilihan workspace harus dirender sebagai menu interaktif.');
assert.match(html, /rel="icon"[^>]*perumnet-favicon\.png/, 'Portal harus menggunakan favicon PerumNet.');
assert.ok(favicon.length > 1000 && favicon.subarray(1,4).toString() === 'PNG', 'Aset favicon harus berupa PNG yang valid.');
assert.match(html, /class="sidebar-brand brand brand-light" href="https:\/\/hotspot\.perumnet\.id"/, 'Logo sidebar harus kembali ke portal hotspot.');
assert.match(html, /class="nav-icon"[^>]*viewBox="0 0 24 24"/, 'Sidebar harus memakai ikon SVG yang konsisten.');
assert.match(html, /class="header-action"[^>]*id="notification-toggle"[^>]*title="Notifikasi"/, 'Header admin harus memakai tombol notifikasi SVG.');
assert.match(html, /id="notification-panel"/, 'Dashboard harus menyediakan panel aktivitas pelanggan.');
assert.match(html, /id="category-filter"/, 'Dashboard harus memisahkan kategori pengguna terdaftar, Free, dan belum login.');
assert.match(html, /id="page-size"[^>]*><option value="10" selected>10<\/option><option value="25">25<\/option><option value="50">50<\/option><option value="100">100<\/option>/, 'Tabel harus menyediakan pilihan 10 sampai 100 data per halaman.');
assert.match(html, /id="monitoring-status"/, 'Dashboard harus menampilkan status monitoring real-time.');
assert.match(html, /id="analytics-panel"/, 'Dashboard harus menampilkan panel grafik di atas tabel perangkat.');
assert.match(html, /id="global-traffic-chart"/, 'Dashboard harus menyediakan grafik bandwidth global gabungan.');
assert.match(html, /id="ssid-usage-chart"/, 'Dashboard harus menyediakan grafik penggunaan setiap SSID.');
assert.match(html, /id="user-usage-chart"/, 'Dashboard harus menyediakan grafik penggunaan per pengguna.');
assert.match(html, /id="monitoring-range"[\s\S]*data-range="1h"[\s\S]*data-range="7d"/, 'Grafik harus menyediakan pilihan periode 1 jam hingga 7 hari.');
assert.match(html, /Bandwidth Saat Ini/, 'Tabel admin harus menampilkan bandwidth setiap pengguna.');
assert.match(html, /Durasi Login/, 'Tabel admin harus menampilkan durasi login.');
assert.match(html, /Data Terpakai/, 'Tabel admin harus menampilkan total penggunaan data.');
assert.match(html, /Hanya akun yang mengisi data\. Free\/Limited tidak disertakan\./, 'Admin harus menjelaskan bahwa CSV mengecualikan akses Free.');
assert.match(html, /data-tab="network"/, 'Dashboard harus menyediakan pengelolaan project dan gateway.');
assert.match(html, /id="scope-project"/, 'Dashboard harus menyediakan filter project global.');
assert.match(html, /id="scope-gateway"/, 'Dashboard harus menyediakan filter gateway global.');
assert.match(html, /id="gateway-list"/, 'Dashboard harus menampilkan daftar identitas gateway.');
assert.match(html, /id="portal-network-list"/, 'Dashboard harus menampilkan routing portal per jaringan gateway.');
assert.match(html, /id="portal-routing-title">Routing Captive Portal/, 'Admin harus menjelaskan routing satu Auth Server URL.');
assert.match(html, /id="forgot-password-screen" class="login-page portal-modal"/, 'Portal harus menyediakan pemulihan kata sandi melalui email.');
assert.match(html, /id="reset-password-screen" class="login-page account-action-page"/, 'Tautan reset harus membuka halaman khusus di luar hotspot.');
assert.match(html, /id="account-status-screen" class="success-page account-action-page"/, 'Verifikasi email harus membuka halaman status khusus.');
assert.doesNotMatch(html, /class="bell">♢/, 'Header admin tidak boleh kembali memakai simbol berlian.');
assert.doesNotMatch(html, /class="privacy-note"><span>♢/, 'Catatan privasi tidak boleh memakai simbol berlian dekoratif.');
assert.match(html, /class="privacy-icon"[^>]*aria-hidden="true"><svg/, 'Catatan privasi harus memakai ikon shield-check SVG.');
assert.doesNotMatch(html, /penawaran dari Kopi Pagi/, 'Persetujuan data harus menggunakan identitas PerumNet.');
assert.doesNotMatch(html, /<span>⚙<\/span>|<span>▦<\/span>/, 'Sidebar tidak boleh kembali memakai emoji sebagai ikon.');
assert.doesNotMatch(html, /Email \/ Username|Username \/ Email|placeholder="Username atau email"/, 'Semua formulir login harus menggunakan email saja.');
assert.match(html, /<form id="login-form"><label>Email<input type="email" placeholder="nama@email\.com"/, 'Login admin harus meminta email secara eksplisit.');
assert.match(html, /placeholder="Masukkan kata sandi"/, 'Login admin harus menyediakan placeholder kata sandi.');
assert.doesNotMatch(html, /value="it@perumnet\.id"/, 'Login admin tidak boleh mengisi email secara statis.');
assert.match(app, /const destinationUrl = 'https:\/\/perumnet\.id'/, 'Tujuan redirect PerumNet harus tetap eksplisit.');
assert.match(app, /const isFreeView = location\.pathname === '\/free'/, 'UI harus mengenali halaman khusus /free.');
assert.match(app, /api\('\/api\/captive\/limited',\{ context:captiveContext \}\)/, 'Tombol halaman free harus memakai otorisasi limited.');
assert.match(app, /accountSsid,freeSsid,welcomeTitle:title/, 'Admin harus menyimpan dua identitas SSID secara bersamaan.');
assert.match(app, /startDestinationRedirect\(\)/, 'Status koneksi harus memulai redirect otomatis.');
assert.match(app, /data-label="Nomor HP"/, 'Tabel mobile harus memiliki label kartu data.');
assert.match(app, /networkAliasPattern/, 'UI harus menolak network alias sebagai SSID.');
assert.match(app, /context\.wlan_name,context\.ssid_name,context\.essid,context\.wifi_name/, 'UI harus memprioritaskan parameter WLAN Ruijie.');
assert.match(app, /\/api\/admin\/notifications/, 'Dashboard harus memuat notifikasi pelanggan dari server.');
assert.match(app, /setInterval\(\(\) => loadNotifications/, 'Dashboard harus memperbarui notifikasi secara berkala.');
assert.match(app, /setInterval\(\(\)=>\{[\s\S]*loadAdminLeads\(\{ silent:true \}\)[\s\S]*\},5000\)/, 'Monitoring client harus diperbarui otomatis setiap lima detik.');
assert.match(app, /\/api\/admin\/export\.csv/, 'Ekspor CSV harus dibuat server agar perangkat Free tidak ikut terunduh.');
assert.match(app, /\/api\/admin\/monitoring/, 'Dashboard harus membaca agregasi monitoring historis dari server.');
assert.match(app, /renderGlobalTrafficChart/, 'UI harus merender grafik gabungan tanpa library eksternal.');
assert.match(app, /renderSsidUsageChart/, 'UI harus merender distribusi per SSID.');
assert.match(app, /renderUserUsageChart/, 'UI harus merender penggunaan per pengguna.');
assert.match(app, /category:'all'.*totalPages:1/, 'UI harus menyimpan state pagination dan kategori tabel.');
assert.match(app, /gatewayId:lead\.gatewayId,macAddress:lead\.mac/, 'Hapus client harus dibatasi pada gateway yang tepat.');
assert.match(app, /\/api\/admin\/network/, 'UI harus membaca struktur project dan gateway dari database.');
assert.match(app, /function renderPortalNetworkRoutes\(\)/, 'UI harus merender mapping Portal Akun dan Portal Free per jaringan.');
assert.match(app, /\/api\/admin\/portal-networks/, 'Admin harus dapat menyimpan routing portal per gateway.');
assert.match(app, /function renderWorkspaceMenu\(\)/, 'UI harus merender pilihan project dan gateway di sidebar.');
assert.match(app, /async function applyAdminScope\(projectId='',gatewayId=''\)/, 'Dropdown sidebar dan filter utama harus memakai scope dashboard yang sama.');
assert.match(app, /workspace-option/, 'UI harus menangani pilihan workspace dari menu sidebar.');
assert.match(app, /\/api\/auth\/forgot-password/, 'UI harus dapat meminta email reset kata sandi.');
assert.match(app, /\/api\/auth\/reset-password/, 'UI harus dapat menyimpan kata sandi baru.');
assert.match(app, /showAccountStatus\('Email berhasil diverifikasi\.','Kembali ke jendela login WiFi/, 'Verifikasi email tidak boleh mengarahkan user ke form hotspot.');
assert.match(css, /body\.admin-view \.sidebar \.sidebar-brand[^}]*background:transparent/, 'Logo admin harus menyatu dengan sidebar.');
assert.match(css, /@media\(max-width:760px\)/, 'Dashboard harus memiliki breakpoint kartu mobile.');
assert.match(css, /\.notification-panel\.open/, 'Panel notifikasi harus memiliki state terbuka yang jelas.');
assert.match(css, /\.scope-bar/, 'Filter scope harus memiliki layout responsif khusus.');
assert.match(css, /\.gateway-grid/, 'Kartu gateway harus memiliki layout desktop dan mobile.');
assert.match(css, /\.portal-network-grid/, 'Routing jaringan harus memiliki layout responsif.');
assert.match(css, /\.portal-route-form/, 'Kartu routing harus menyediakan form yang rapi.');
assert.match(css, /\.portal-profile-grid/, 'Profil portal admin harus memiliki layout responsif khusus.');
const desktopGatewayTableWidth = css.lastIndexOf('body.admin-view table{min-width:1880px}');
const mobileGatewayTableReset = css.lastIndexOf('body.admin-view table{display:block;width:100%;min-width:0;max-width:100%');
const finalMobileTableReset = css.lastIndexOf('body.admin-view table{min-width:0}');
assert.ok(Math.max(mobileGatewayTableReset,finalMobileTableReset) > desktopGatewayTableWidth, 'Aturan mobile harus membatalkan lebar minimum tabel monitoring.');
assert.match(css, /body\.admin-view \.stats\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/, 'Statistik mobile harus tampil tanpa carousel horizontal yang terpotong.');
assert.match(css, /\.analytics-grid/, 'Panel monitoring harus memiliki layout grafik responsif.');
assert.match(css, /\.workspace-switcher\.open \.workspace-menu/, 'Menu workspace harus memiliki state buka yang jelas.');
assert.match(css, /\.workspace-option\.active/, 'Project atau gateway terpilih harus memiliki state visual aktif.');
assert.match(css, /body\.admin-view \.analytics-card\{width:100%;min-width:0;max-width:100%/, 'Panel grafik mobile harus dibatasi pada lebar viewport.');

console.log('Responsive UI contract: PASS');
